<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f8757681-2203-4ba5-afde-11f65b9fef32</elementGuidId>
    <imagePath></imagePath>
    <name>button_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/main[1]/div[1]/div[2]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.sc-59714b69-2</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'sc-59714b69-0 sc-59714b69-2 gOQBaY jYkVQk')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>sc-59714b69-0 sc-59714b69-2 gOQBaY jYkVQk</value>
        <webElementGuid>886ce80e-4add-46bb-b775-c28bf9974397</webElementGuid>
    </webElementProperties>
</WebElementEntity>