<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4dc313e6-aaf7-4ab2-94e0-822603d51260</elementGuidId>
    <imagePath></imagePath>
    <name>span_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.sc-4eccdd42-1</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'sc-4eccdd42-1 isbxaz')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>sc-4eccdd42-1 isbxaz</value>
        <webElementGuid>b0150f15-1e7d-43d2-8334-07719eebe666</webElementGuid>
    </webElementProperties>
</WebElementEntity>